# Generated by Django 6.0.2 on 2026-03-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=50)),
                ('programa', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Aprendiz Aplica', 'Aprendiz Aplica'), ('Empresa Solicita', 'Empresa Solicita'), ('En Proceso de Selección', 'En Proceso de Selección'), ('Contratado', 'Contratado'), ('Final Contrato', 'Final Contrato'), ('Cancelado', 'Cancelado'), ('Alumno Retirado', 'Alumno Retirado'), ('Aplazado', 'Aplazado'), ('Pendiente Por Certificar', 'Pendiente Por Certificar'), ('Bajo Rendimiento Académico', 'Bajo Rendimiento Académico'), ('Aprendiz no interesado en contrato', 'Aprendiz no interesado en contrato'), ('Inhabilitado Por Actualización', 'Inhabilitado Por Actualización'), ('Contrato No Registrado', 'Contrato No Registrado'), ('Fallecido', 'Fallecido')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('sector_economico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector Económico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
