# Generated by Django 6.0.2 on 2026-03-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas_excel/%Y/%m/', verbose_name='Archivo')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total Registros')),
                ('registros_nuevos', models.IntegerField(default=0, verbose_name='Registros Nuevos')),
                ('registros_actualizados', models.IntegerField(default=0, verbose_name='Registros Actualizados')),
                ('errores', models.TextField(blank=True, null=True, verbose_name='Errores')),
                ('procesado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesado Por')),
            ],
            options={
                'verbose_name': 'Carga Excel',
                'verbose_name_plural': 'Cargas Excel',
                'db_table': 'cargas_excel',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('sector_economico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector Económico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte')], default='CC', max_length=2, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('programa_formacion', models.CharField(max_length=200, verbose_name='Programa de Formación')),
                ('ficha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Ficha')),
                ('fecha_inicio_etapa_practica', models.DateField(blank=True, null=True, verbose_name='Inicio Etapa Práctica')),
                ('fecha_fin_etapa_practica', models.DateField(blank=True, null=True, verbose_name='Fin Etapa Práctica')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INHABILITADO_ACT', 'Inhabilitado por Actualización'), ('PROCESO_SELECCION', 'Proceso de Selección'), ('PROCESO_ABIERTO', 'Proceso de Selección Abierto'), ('SIN_CONTRATO', 'Contrato no Registrado')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('archivo_origen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Archivo de Origen')),
                ('empresa_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='core.empresa', verbose_name='Empresa Vinculada')),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
                'db_table': 'aprendices',
                'ordering': ['-fecha_carga'],
                'indexes': [models.Index(fields=['estado'], name='aprendices_estado_b0f46e_idx'), models.Index(fields=['numero_documento'], name='aprendices_numero__064259_idx'), models.Index(fields=['empresa_vinculada'], name='aprendices_empresa_73d912_idx')],
            },
        ),
    ]
