# Generated by Django 6.0.2 on 2026-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='programa_formacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Programa de Formación'),
        ),
    ]
