# Generated by Django 6.0.2 on 2026-03-13 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='cantidad_de_contratos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='centro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='empresa_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_lectiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_practica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='ficha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='razon_social_empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='regional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Aprendiz Aplica', 'Aprendiz Aplica'), ('Empresa Solicita', 'Empresa Solicita'), ('En Proceso de Selección', 'En Proceso de Selección'), ('Contratado', 'Contratado'), ('Final Contrato', 'Final Contrato'), ('Cancelado', 'Cancelado'), ('Alumno Retirado', 'Alumno Retirado'), ('Aplazado', 'Aplazado'), ('Pendiente Por Certificar', 'Pendiente Por Certificar'), ('Bajo Rendimiento Académico', 'Bajo Rendimiento Académico'), ('Aprendiz no interesado en contrato', 'Aprendiz no interesado en contrato'), ('Inhabilitado Por Actualización', 'Inhabilitado Por Actualización'), ('Contrato No Registrado', 'Contrato No Registrado'), ('Fallecido', 'Fallecido')], default='Disponible', max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='programa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
