# Generated by Django 6.0.2 on 2026-03-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aprendiz_programa_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='estado_aprendiz',
            field=models.CharField(default='DISPONIBLE', max_length=50, verbose_name='Estado Aprendiz'),
        ),
    ]
