# Generated by Django 6.0.2 on 2026-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aprendiz_archivo_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Aprendiz Aplica', 'Aprendiz Aplica'), ('Empresa Solicita', 'Empresa Solicita'), ('En Proceso de Selección', 'En Proceso de Selección'), ('Proceso de Selección Abierto', 'Proceso de Selección Abierto'), ('Contratado', 'Contratado'), ('Final Contrato', 'Final Contrato'), ('Cancelado', 'Cancelado'), ('Alumno Retirado', 'Alumno Retirado'), ('Aplazado', 'Aplazado'), ('Pendiente Por Certificar', 'Pendiente Por Certificar'), ('Bajo Rendimiento Académico', 'Bajo Rendimiento Académico'), ('Aprendiz no interesado en contrato', 'Aprendiz no interesado en contrato'), ('Inhabilitado Por Actualización', 'Inhabilitado Por Actualización'), ('Contrato No Registrado', 'Contrato No Registrado'), ('Fallecido', 'Fallecido')], default='Disponible', max_length=100),
        ),
    ]
