# Generated by Django 6.0.2 on 2026-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aprendiz_estado_aprendiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INHABILITADO_ACT', 'Inhabilitado por Actualización'), ('PROCESO_SELECCION', 'Proceso de Selección'), ('PROCESO_ABIERTO', 'Proceso de Selección Abierto'), ('CONTRATO_NO_REGISTRADO', 'Contrato no Registrado')], default='DISPONIBLE', max_length=25, verbose_name='Estado'),
        ),
    ]
