# Generated by Django 6.0.2 on 2026-03-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aprendiz_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprendiz',
            name='fecha_fin_etapa_practica',
        ),
        migrations.RemoveField(
            model_name='aprendiz',
            name='fecha_inicio_etapa_practica',
        ),
        migrations.RemoveField(
            model_name='aprendiz',
            name='programa_formacion',
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='especializacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialización'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='etapa_electiva',
            field=models.DateField(blank=True, null=True, verbose_name='Etapa Electiva'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='etapa_practica',
            field=models.DateField(blank=True, null=True, verbose_name='Etapa Práctica'),
        ),
    ]
