from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('aprendices/', views.lista_aprendices, name='lista_aprendices'),
    path('aprendices/<int:pk>/', views.detalle_aprendiz, name='detalle_aprendiz'),
    path('aprendices/<int:pk>/editar/', views.editar_aprendiz, name='editar_aprendiz'),
    path('aprendices/<int:pk>/cambiar-estado/', views.cambiar_estado, name='cambiar_estado'),
    path('aprendices/<int:pk>/eliminar/', views.eliminar_aprendiz, name='eliminar_aprendiz'),
    path('aprendices/<int:pk>/confirmar-eliminar/', views.confirmar_eliminar_aprendiz, name='confirmar_eliminar_aprendiz'),
    path('aprendices/<int:pk>/eliminar-ajax/', views.eliminar_aprendiz_ajax, name='eliminar_aprendiz_ajax'),
    path('aprendices/eliminacion-masiva/', views.eliminacion_masiva_aprendices, name='eliminacion_masiva_aprendices'),
    path('aprendices/filtro-eliminacion/', views.obtener_filtro_eliminacion, name='obtener_filtro_eliminacion'),
    path('aprendices/eliminar-todos/', views.eliminar_todos_aprendices, name='eliminar_todos_aprendices'),
    path('aprendices/estadisticas-totales/', views.estadisticas_totales, name='estadisticas_totales'),
    path('aprendices/crear-datos-prueba/', views.crear_datos_prueba, name='crear_datos_prueba'),
    path('aprendices/validar-excel/', views.validar_excel_ajax, name='validar_excel_ajax'),
    path('carga-excel/', views.carga_excel, name='carga_excel'),
    path('carga-excel-nueva/', views.carga_excel_nueva, name='carga_excel_nueva'),
    path('resultado-carga/', views.resultado_carga, name='resultado_carga'),
    path('empresas/', views.lista_empresas, name='lista_empresas'),
    path('empresas/<int:pk>/', views.detalle_empresa, name='detalle_empresa'),
    path('reportes/', views.reportes, name='reportes'),
    path('reportes/export/excel/', views.exportar_reportes_excel, name='exportar_reportes_excel'),
    path('reportes/export/pdf/', views.exportar_reportes_pdf, name='exportar_reportes_pdf'),
    path('reportes/export/csv/', views.exportar_reportes_csv, name='exportar_reportes_csv'),
    path('reportes/accion/actualizar-inhabilitados/', views.accion_actualizar_inhabilitados, name='accion_actualizar_inhabilitados'),
    path('reportes/accion/contactar-contrato-no-registrado/', views.accion_contactar_contrato_no_registrado, name='accion_contactar_contrato_no_registrado'),
    path('reportes/accion/ver-detalles/', views.accion_ver_detalles, name='accion_ver_detalles'),
    path('guia-clasificacion/', views.guia_clasificacion, name='guia_clasificacion'),
]
